[env:ttgo-t-display-16mb]
platform = espressif32
board = esp32dev
; Menggunakan partisi 16MB (Pastikan file ini ada di support_files atau gunakan default)
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB

extra_scripts =
	${env.extra_scripts}
	pre:support_files/nvs_script.py

; Arahkan folder board ke folder baru untuk TTGO
build_src_filter = ${env.build_src_filter} +<../boards/Ttgo>

build_flags =
	${env.build_flags}
	-Iboards/Ttgo
	-DOTA_TAG='"ttgo"'
	-DTTGO_T_DISPLAY=1
	-DDEVICE_NAME='"TTGO T-Display"'
	-DBOARD_HAS_PSRAM=0 ; Set ke 1 jika TTGO kamu varian yang punya PSRAM
	
	-DPART_16MB=1
	-DROTATION=1
	-DHAS_BTN=1
	
	; Konfigurasi PIN sesuai Bruce untuk TTGO
	-DSEL_BTN=35
	-DUP_BTN=0
	-DDW_BTN=35
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"BTN"'
	-DADC_EN=14
	
	; Konfigurasi Layar ST7789 TTGO (Sesuai Hardware Asli)
	-DST7789_DRIVER=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DTFT_MOSI=19
	-DTFT_SCLK=18
	-DTFT_CS=5
	-DTFT_DC=16
	-DTFT_RST=23
	-DTFT_BL=4
	
	; Offset layar TTGO (Sesuai Bruce)
	-DTFT_IPS=1
	-D CGRAM_OFFSET=1
	-D TFT_COL_OFS1=52
	-D TFT_ROW_OFS1=40
	-D TFT_COL_OFS2=53
	-D TFT_ROW_OFS2=40

	-DFP=1
	-DFM=2
	-DFG=3

	; Kecepatan Flash
	-D BOARD_FLASH_MODE=dio
	-D BOARD_FLASH_FREQ=40m

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button
  
